package universitysystem;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu_department = new javax.swing.JMenu();
        jMenu_instructor = new javax.swing.JMenu();
        jMenu_classroom = new javax.swing.JMenu();
        jMenu_courses = new javax.swing.JMenu();
        jMenu_prerequisite = new javax.swing.JMenu();
        jMenu_time_slot = new javax.swing.JMenu();
        jMenu_section = new javax.swing.JMenu();
        jMenu_student = new javax.swing.JMenu();
        jMenu_takes = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu1.setText("File");
        jMenuBar3.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar3.add(jMenu2);

        jMenu5.setText("File");
        jMenuBar4.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar5.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar5.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setBackground(new java.awt.Color(0, 51, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel1.setText("ABC UNIVERSITY SYSTEM");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\universitydb\\UniversitySystem\\src\\universitysystem\\milky-way-2695569_1920.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 800, 500));

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 255));

        jMenu_department.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_department.setText("DEPARTMENTS");
        jMenu_department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_departmentMouseClicked(evt);
            }
        });
        jMenu_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_departmentActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_department);

        jMenu_instructor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_instructor.setText("INSTRUCTORS");
        jMenu_instructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_instructorMouseClicked(evt);
            }
        });
        jMenu_instructor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_instructorActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_instructor);

        jMenu_classroom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_classroom.setText("CLASSROOMS");
        jMenu_classroom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_classroomMouseClicked(evt);
            }
        });
        jMenu_classroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_classroomActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_classroom);

        jMenu_courses.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_courses.setText("COURSES");
        jMenu_courses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_coursesMouseClicked(evt);
            }
        });
        jMenu_courses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_coursesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_courses);

        jMenu_prerequisite.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_prerequisite.setText("PREREQUISITES");
        jMenu_prerequisite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_prerequisiteMouseClicked(evt);
            }
        });
        jMenu_prerequisite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_prerequisiteActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_prerequisite);

        jMenu_time_slot.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_time_slot.setText("TIME SLOTS");
        jMenu_time_slot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_time_slotMouseClicked(evt);
            }
        });
        jMenu_time_slot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_time_slotActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_time_slot);

        jMenu_section.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_section.setText("SECTIONS");
        jMenu_section.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_sectionMouseClicked(evt);
            }
        });
        jMenu_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_sectionActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_section);

        jMenu_student.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_student.setText("STUDENTS");
        jMenu_student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_studentMouseClicked(evt);
            }
        });
        jMenu_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_studentActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_student);

        jMenu_takes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jMenu_takes.setText("ENROLL");
        jMenu_takes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu_takesMouseClicked(evt);
            }
        });
        jMenu_takes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu_takesActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu_takes);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_departmentActionPerformed
    
    }//GEN-LAST:event_jMenu_departmentActionPerformed

    private void jMenu_instructorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_instructorActionPerformed

    }//GEN-LAST:event_jMenu_instructorActionPerformed
    
    private void jMenu_departmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_departmentMouseClicked
        DepartmentForm department = new DepartmentForm();
        department.setVisible(true);
    }//GEN-LAST:event_jMenu_departmentMouseClicked

    private void jMenu_instructorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_instructorMouseClicked
        InstructorForm instructor = new InstructorForm();
        instructor.setVisible(true);
    }//GEN-LAST:event_jMenu_instructorMouseClicked

    private void jMenu_classroomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_classroomMouseClicked
        ClassroomForm classroom = new ClassroomForm();
        classroom.setVisible(true);
    }//GEN-LAST:event_jMenu_classroomMouseClicked

    private void jMenu_classroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_classroomActionPerformed

    }//GEN-LAST:event_jMenu_classroomActionPerformed

    private void jMenu_coursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_coursesActionPerformed

    }//GEN-LAST:event_jMenu_coursesActionPerformed

    private void jMenu_coursesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_coursesMouseClicked
        CourseForm course = new CourseForm();
        course.setVisible(true);
    }//GEN-LAST:event_jMenu_coursesMouseClicked

    private void jMenu_prerequisiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_prerequisiteActionPerformed

    }//GEN-LAST:event_jMenu_prerequisiteActionPerformed

    private void jMenu_prerequisiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_prerequisiteMouseClicked
        PrerequisiteForm prerequisite = new PrerequisiteForm();
        prerequisite.setVisible(true);
    }//GEN-LAST:event_jMenu_prerequisiteMouseClicked

    private void jMenu_time_slotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_time_slotActionPerformed

    }//GEN-LAST:event_jMenu_time_slotActionPerformed

    private void jMenu_time_slotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_time_slotMouseClicked
        TimeSlotForm time_slot = new TimeSlotForm();
        time_slot.setVisible(true);
    }//GEN-LAST:event_jMenu_time_slotMouseClicked

    private void jMenu_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_sectionActionPerformed

    }//GEN-LAST:event_jMenu_sectionActionPerformed

    private void jMenu_sectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_sectionMouseClicked
        SectionForm section = new SectionForm();
        section.setVisible(true);
    }//GEN-LAST:event_jMenu_sectionMouseClicked

    private void jMenu_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_studentActionPerformed

    }//GEN-LAST:event_jMenu_studentActionPerformed

    private void jMenu_studentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_studentMouseClicked
        StudentForm student = new StudentForm();
        student.setVisible(true);
    }//GEN-LAST:event_jMenu_studentMouseClicked

    private void jMenu_takesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu_takesActionPerformed

    }//GEN-LAST:event_jMenu_takesActionPerformed

    private void jMenu_takesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu_takesMouseClicked
        TakesForm takes = new TakesForm();
        takes.setVisible(true);
    }//GEN-LAST:event_jMenu_takesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenu jMenu_classroom;
    private javax.swing.JMenu jMenu_courses;
    private javax.swing.JMenu jMenu_department;
    private javax.swing.JMenu jMenu_instructor;
    private javax.swing.JMenu jMenu_prerequisite;
    private javax.swing.JMenu jMenu_section;
    private javax.swing.JMenu jMenu_student;
    private javax.swing.JMenu jMenu_takes;
    private javax.swing.JMenu jMenu_time_slot;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
